# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  PREPARED_DATA: prepared
  TRAIN_DATA: train.tsv
  TEST_DATA: test.tsv
  FEATURIZED_DATA: features
  FEATURIZED_TRAIN_DATA: train.pkl
  FEATURIZED_TEST_DATA: test.pkl
  MODEL_DIR: model
  MODEL_NAME: model.pkl

## Use the function below, if you use URL links as your data source
#source_data_url: https://drive.google.com/file/d/1agyr-U_DGlH43ntuPmAoUZ5Q4veXK_Pd/view?usp=sharing
# source_download_dir:
#   data_dir: data
#   data_file: data.xml

## Use the function below if you have already downloaded the dataset and the data source is located on your local PC.
source_data_dirs:
  - ../NLP-dataset
local_data_dirs:
  data_dir: data
  data_file: data.xml

plots:
  PRC: prc.json
  ROC: roc.json

metrics:
  SCORES: scores.json
